[Paths]
Prefix=/opt/Qt5.14.2-arm64
Headers=/opt/Qt5.14.2-arm64/include
Libraries=/opt/Qt5.14.2-arm64/lib
Plugins=/opt/Qt5.14.2-arm64/plugins
Qml2Imports=/opt/Qt5.14.2-arm64/qml
ArchData=/opt/Qt5.14.2-arm64
HostPrefix=/opt/Qt5.14.2-host
HostData=/opt/Qt5.14.2-host
HostBinaries=/opt/Qt5.14.2-host/bin
HostLibraries=/opt/Qt5.14.2-host/lib
